[package]
name = "psg-calendar-to-ballbreaker"
version = "0.4.1"
edition = "2024"

[dependencies]
anyhow = "1.0.103"
chrono = "0.4.45"
clokwerk = "0.4.0"
env_logger = "0.11.11"
gcal_rs = "0.1.7"
log = "0.4.33"
rusqlite = { version = "0.40.1", features = ["bundled"] }
teloxide = { git = "https://github.com/teloxide/teloxide.git", rev = "0ca6f7d22410fc043bc52c165f2e69741fd83f1c", features = ["macros"] }
tokio = "1.52.3"

[profile.release]
strip = true
lto = true
codegen-units = 1
